server {
    listen 80;
    root /var/www/public;
    index index.php;

    location = /favicon.ico {
        try_files /assets/img/favicon.ico =404;
        access_log off;
        log_not_found off;
        expires 7d;
    }

    location / {
        try_files $uri /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass app:9000;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }

    location ~ /\. { deny all; }
}
